### PR TITLE
Cleanup, Time Scale & Styles that work with Firefox

### PR DESCRIPTION
**Pull request by tschw**
The code is pretty chaotic, but the GUI looks really nice :-). Is it abandoned?

Anyways, I saved some cleanup steps before stripping out the tweening / data model stuff to repurpose it for keyframes. Use whatever you like - or nothing at all. Just saying thanks...

### CODE REVIEW

**Comment by zz85** [comment]
I agree with you, the code is chaotic. I wanted to emulate a unidirectional data driven model (like React+Flux) but I guess I didn't do a good job... :grin: 

This project is still not abandoned though, just taking a break ;) I'm hope to finish up a little animation demo with this sometime soon...

Thanks for your contribution, I'll try to look at what you have! :)

**Comment by tschw** [comment]
> I wanted to emulate a unidirectional data driven model (like React+Flux) but I guess I didn't do a good job..

Oh, my comment wasn't about that, actually. The code as a whole just reads very much cowboy-coded without much time "wasted" on cleaning up. Got me amazed you could pull it off, in fact. I certainly couldn't have written it that way, and maybe I'm just jealous for your rapid prototyping skills :-).

**Comment by zz85** [comment]
haha, sometimes going too fast at the start may just slow me down later. btw it seems like unfortunately i've moved some of my files around too as well (didn't push my commits earlier sorry). I'll try to see if I can resolve the merge manually. nice branch name btw! =D

**Comment by zz85** [comment]
I rebased and merged 2 of your commits
- i already moved some files around, so i skipped the first commit, maybe i should refactor them sometime again
- using a non-linear sliding scale makes some sense!
- smaller diamonds looks good, but perhaps when i make this app touch compatible again, it might have to be enlarged... :)
- probably I might be missing things, but I'm open to more improvements!

**Comment by tschw** [comment]
> probably I might be missing things, but I'm open to more improvements!

Well, I forked it:

https://github.com/tschw/timeliner_gui/commits/master

Therefore, your timeliner's GUI finally has made it into Three.js. It's currently very much stripped down, but it should be possible to reactivate some stuff:

https://github.com/tschw/three.js/commit/a3227e23a2423caad8166becb99db2f5e25db580

**Pull request closed without merging**
